name: Ci


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: windows-latest


    steps:

    - name: Download

      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract

      run: Expand-Archive ngrok.zip

    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    # Install OBS Studio
    - name: Install OBS Studio
      run: |
        curl -L -o OBS-Studio-30.2.3-Windows-Installer.exe https://cdn-fastly.obsproject.com/downloads/OBS-Studio-30.2.3-Windows-Installer.exe
        start /wait OBS-Studio-30.2.3-Windows-Installer.exe /S

    # Install BlueStacks
    - name: Install BlueStacks
      run: |
        curl -L -o BlueStacks-Installer.exe "https://cloud.bluestacks.com/api/getdownloadnow?platform=win&win_version=10&mac_version=&client_uuid=1307ae4f-c79d-408c-8b92-5e20bd89a5b8&app_pkg=&platform_cloud=%257B%2522description%2522%253A%2522Chrome%2520127.0.0.0%2520on%2520Windows%252010%252064-bit%2522%252C%2522layout%2522%253A%2522Blink%2522%252C%2522manufacturer%2522%253Anull%252C%2522name%2522%253A%2522Chrome%2522%252C%2522prerelease%2522%253Anull%252C%2522product%2522%253Anull%252C%2522ua%2522%253A%2522Mozilla%252F5.0%2520(Windows%2520NT%252010.0%253B%2520Win64%253B%2520x64)%2520AppleWebKit%252F537.36%2520(KHTML%252C%2520like%2520Gecko)%2520Chrome%252F127.0.0.0%2520Safari%252F537.36%2522%252C%2522version%2522%253A%2522127.0.0.0%2522%252C%2522os%2522%253A%257B%2522architecture%2522%253A64%252C%2522family%2522%253A%2522Windows%2522%252C%2522version%2522%253A%252210%2522%257D%257D&preferred_lang=en&utm_source=&utm_medium=&gaCookie=GA1.1.1721922740.1724296119&gclid=&clickid=&msclkid=&affiliateId=&offerId=&transaction_id=&aff_sub=&first_landing_page=https%253A%252F%252Fwww.bluestacks.com%252Fbluestacks-5.html&referrer=https%253A%252F%252Fwww.google.com%252F&download_page_referrer=https%3A%2F%2Fwww.bluestacks.com%2Fbluestacks-5.html&utm_campaign=bluestacks-5-en&user_id=&exit_utm_campaign=bluestacks5-page-en&incompatible=false&bluestacks_version=bs5&device_memory=8&device_cpu_cores=4"
        start /wait BlueStacks-Installer.exe /S

    # Install Visual Studio Code
    - name: Install Visual Studio Code
      run: |
        curl -L -o VSCodeSetup-x64.exe https://update.code.visualstudio.com/latest/win32-x64/stable
        start /wait VSCodeSetup-x64.exe /SILENT
        
    - name: Create Tunnel

      run: .\ngrok\ngrok.exe tcp 3389
